import { StyleSheet } from 'react-native';
import Colors from '../../../Config/Colors';

export default StyleSheet.create({
    container: {
        flex: 1,
         backgroundColor:'#E12F5B',
    },
    mainview:{
        flex: 1,
        marginTop:10,
        justifyContent: 'center',
        marginLeft:10,
        marginRight:10,
    },
    textinput: {
    fontSize: 14,
    color: '#98a9ae',
    borderWidth: 1,
    borderColor: '#BED8D4',
    padding: 10,
    marginLeft:10,
    marginRight:10,
    fontFamily:'Avenir-Book',
    },
    textinputLast: {
        fontSize: 16,
        color: '#98a9ae',
        borderWidth: 1,
        borderColor: '#BED8D4',
        padding: 10,
        marginLeft:10,
        marginRight:10,
        height:80,
        textAlignVertical:'top',
        fontFamily:'Avenir-Book',
        
        },
    button: {
        borderRadius: 50, 
         paddingHorizontal: 12,
        paddingVertical: 15,
        alignItems: 'center',
        backgroundColor: '#52C7FA',
        marginHorizontal: 5,
        marginTop: 25,
        marginLeft:65,
        marginRight:65,
        marginBottom:50,
    },
   
    buttontext: {
        fontSize: 16,
        color: Colors.white
    },
   
   picker: {
    fontSize: 16,
    color: Colors.primary,
    borderWidth: 2,
    borderRadius: 4,
    borderColor: '#BED8D4',
    padding: 10,
    marginVertical: 10
   },
   backicon: {
       width: 22,
       height: 22,
       marginLeft: 20
   },
   pickerview: {
       width: '100%',
   },
   pickerviewNew: {
    width: '95%',
    backgroundColor:'#66CDCC',
    marginTop:30,
    marginLeft:10,
    marginRight:20,
    height:50,
    flexDirection:'row',
    borderRadius:10,
    // borderWidth:1,
},
   addiconview: {
    marginLeft:10,
    marginTop:10,
    flexDirection:'row',
  },
  attachicon: {
      marginLeft:10,
      width: 25,
      height: 25,
      tintColor:'#fff',
  },
  mainView1:{
    backgroundColor: "#E12F5B",
    width: "100%",
    height: 60,
    marginTop: 10,
    flexDirection: "row",
  },
  
  stepText:{
    marginTop: 20,
    marginBottom: 5,
    fontSize: 15,
    marginLeft: 50,
    color: "#fff",
  },
  stepText1:{
    marginTop: 20,
    marginBottom: 5,
    fontSize: 15,
    marginLeft: 50,
    // color: "#6F7C80",
    color: "#EFEFF4",
  },
  step2Text:{
    marginTop: 30,
    marginBottom: 5,
    fontSize: 15,
    marginLeft: 25,
    height: 1,
    width: 100,
    // color: "#fff",
    backgroundColor: "#FDFDFD",
  },
  stepLine:{
    marginTop: 20,
    marginBottom: 5,
    fontSize: 15,
    marginLeft: 25,
    color: "#fff",
  },
  stepLine1:{
    marginTop: 20,
    marginBottom: 5,
    fontSize: 15,
    marginLeft: 25,
    // color: "#6F7C80",
    color:'#EFEFF4',
  },
  scrollView:{
    marginTop: 30,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#fff",
  },
  viewStep1:{
    width: "95%",
    height: 90,
    marginTop: 40,
    marginLeft: 10,
    backgroundColor: "#fff",
    shadowColor: Colors.black,
    borderWidth: 0.1,
    borderColor: '#BED8D4',
    shadowOpacity: 0.5,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0,
    },
  },
  viewStepSecond1:{
    width: "95%",
    height: 150,
    marginTop: 20,
    marginLeft: 10,
    backgroundColor: "#fff",
    shadowColor: Colors.black,
    borderWidth: 0.1,
    borderColor: '#BED8D4',
    shadowOpacity: 0.5,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0,
    },
  },
  jobTitle:{
    fontSize: 15,
    color: "#6f7c80",
    marginLeft: 10,
    marginTop: 15,
    marginBottom: 5,
    fontWeight: "bold",
  },
  attachTitle:{
    fontSize: 15,
    color: "#fff",
    marginLeft: 20,
     marginTop: 5,
    marginBottom: 5,
    fontWeight: "bold",
  },
  view2:
  {
    width: "95%",
    height: 200,
    marginTop: 20,
    marginLeft: 10,
    backgroundColor: "#fff",
    shadowColor: Colors.black,
    borderWidth: 0.1,
    borderColor: '#BED8D4',
    shadowOpacity: 0.5,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0,
    },
  },
  resignText:{
    fontSize: 15,
    color: "#6F7C80",
    marginLeft: 10,
    marginTop: 12,
    marginBottom: 5,
    fontWeight: "bold",
  },
  subView:{ width: "92%",},
  cityText:{
    fontSize: 15,
    color: "#6F7C80",
    marginLeft: 10,
    marginTop: 20,
    marginBottom: 5,
    fontWeight: "bold",
  },
  pickerViewText:{
    width: "93%",
    marginLeft: 10,
    marginRight: 10,
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#BED8D4",
  },
  imageComment:{
    width: 20,
    height: 20,
    marginTop: 15,
  },
  imageView:{
    width: "93%",
    marginLeft: 10,
    marginRight: 10,
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#BED8D4",
  },
  viewPicker1:{
    width: "93%",
    marginLeft: 10,
    marginRight: 10,
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#BED8D4",
  },
  viewPicker2:{
    width: "93%",
    marginLeft: 10,
    marginRight: 10,
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#BED8D4",
  },
  
})